In [86]:
import numpy as np
import pandas as pd

In [87]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [88]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [89]:
time.sample(5)

                    date                                                msg
748  2013-11-24 00:43:00  . Мне 37. Поцелую женщине 50-55лет. Жду смс фо...
303  2013-07-28 00:35:00          м37жен ищю любовницу  Запорожьэ0968673122
801  2013-06-26 23:54:00  заберу на авто М до 20 к себе в кроватку Ж 35 ...
979  2013-11-19 00:38:00  Д 21 Замужем ищу любовника для редких встреч Катя
571  2014-08-05 00:03:00  ПРИГЛАШУ НА НОЧНОЙ ПЛЯЖ СТРОЙНУЮ МАЛЫШКУ.ПРИЕД...

In [90]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [91]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

#### Handling dates

In [92]:
# 1. converting info datetime type
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [93]:
# 2. Extract Year
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
490 2019-06-21        2254       16       4       2019
116 2019-04-23        4523       13       1       2019
498 2018-08-07        3508       28       1       2018
351 2018-12-23        2056       28       1       2018
988 2019-02-03        5022        2      43       2019

In [94]:
#extract months
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
698 2018-10-03        7567       22       1       2018             10
622 2018-09-21        3234       25       2       2018              9
646 2018-09-01        7399        0      39       2018              9
449 2019-03-24        4523       13       1       2019              3
188 2019-06-25        1123       25       1       2019              6

In [95]:
# month name
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
395,2019-08-06,7300,9,46,2019,8,August
409,2018-09-07,6478,2,2,2018,9,September
523,2019-06-18,3629,9,4,2019,6,June
601,2019-11-24,6592,25,12,2019,11,November
435,2018-10-20,4847,26,9,2018,10,October

In [96]:
#extract days
date['date_day']= date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
866,2019-11-27,1307,1,7,2019,11,November,27
865,2018-10-13,803,23,3,2018,10,October,13
745,2019-05-18,6910,21,1,2019,5,May,18
714,2019-08-07,4659,1,1,2019,8,August,7
334,2019-10-27,1130,14,48,2019,10,October,27

In [97]:
#week (0,1,2,3,4,5,6)
date['date_week'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_week
775,2019-05-27,5968,13,11,2019,5,May,27,0
607,2019-05-27,3685,0,1,2019,5,May,27,0
905,2018-08-22,133,16,2,2018,8,August,22,2
134,2019-11-17,6049,16,1,2019,11,November,17,6
107,2018-12-29,1225,13,60,2018,12,December,29,5

In [98]:
date.drop(columns=['product_id','city_id'], inplace= True)
# day name - sunday, monday
date['date_day_name'] = date['date'].dt.day_name()
date.sample(5)

# starts from monday  0- Monday , 1- Tuesday , ....,6- Sunday

,date,orders,date_year,date_month_no,date_month_name,date_day,date_week,date_day_name
19,2019-04-13,20,2019,4,April,13,5,Saturday
771,2019-06-17,1,2019,6,June,17,0,Monday
890,2018-09-03,2,2018,9,September,3,0,Monday
200,2019-02-06,5,2019,2,February,6,2,Wednesday
306,2019-08-01,2,2019,8,August,1,3,Thursday

In [99]:
# is weekend or not??
date['weekend'] = np.where(date['date_day_name'].isin(['Sunday','Saturday']),1,0)
date.sample(5)

,date,orders,date_year,date_month_no,date_month_name,date_day,date_week,date_day_name,weekend
333,2019-10-31,71,2019,10,October,31,3,Thursday,0
124,2018-11-22,23,2018,11,November,22,3,Thursday,0
88,2019-10-11,10,2019,10,October,11,4,Friday,0
541,2018-12-10,13,2018,12,December,10,0,Monday,0
770,2018-09-10,1,2018,9,September,10,0,Monday,0

In [100]:
# week of the year
date['date_year_week']= date['date'].dt.isocalendar().week
date.sample(5)

,date,orders,date_year,date_month_no,date_month_name,date_day,date_week,date_day_name,weekend,date_year_week
558,2019-06-26,2,2019,6,June,26,2,Wednesday,0,26
263,2019-11-03,2,2019,11,November,3,6,Sunday,1,44
811,2018-11-03,8,2018,11,November,3,5,Saturday,1,44
400,2019-04-18,1,2019,4,April,18,3,Thursday,0,16
932,2019-07-19,1,2019,7,July,19,4,Friday,0,29

In [101]:
date.drop(columns=['date_month_no','date_month_name','date_day','date_week'], inplace= True)
#quater of the year
date['quarter']=date['date'].dt.quarter
#semester of the year
date['semester']= np.where(date['quarter'].isin([1,2]),1,2)
date.sample(5)

,date,orders,date_year,date_day_name,weekend,date_year_week,quarter,semester
876,2019-11-05,2,2019,Tuesday,0,45,4,2
34,2019-04-09,12,2019,Tuesday,0,15,2,1
827,2019-07-05,24,2019,Friday,0,27,3,2
22,2019-09-13,6,2019,Friday,0,37,3,2
256,2019-07-28,1,2019,Sunday,1,30,3,2

#### Time

In [110]:
#how many time passed away:\

#to calculate today date:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 4, 20, 49, 37, 564669)

In [111]:
time_diff = today - date.date
time_diff

0     2276 days 20:49:37.564669
1     2758 days 20:49:37.564669
2     2689 days 20:49:37.564669
3     2391 days 20:49:37.564669
4     2614 days 20:49:37.564669
                 ...
995   2704 days 20:49:37.564669
996   2645 days 20:49:37.564669
997   2493 days 20:49:37.564669
998   2558 days 20:49:37.564669
999   2332 days 20:49:37.564669
Name: date, Length: 1000, dtype: timedelta64[us]

In [112]:
# we need how many days has passed:
time_diff.dt.days

0      2276
1      2758
2      2689
3      2391
4      2614
       ...
995    2704
996    2645
997    2493
998    2558
999    2332
Name: date, Length: 1000, dtype: int64

In [116]:
#month passed
(time_diff.dt.days / 30).astype('int')

0      75
1      91
2      89
3      79
4      87
       ..
995    90
996    88
997    83
998    85
999    77
Name: date, Length: 1000, dtype: int64

In [119]:
time.sample(5)

                    date                                                msg
833  2016-04-15 22:41:00  ИЩЮ КОЛБИНА ЖЕНЮ. ОН УЧИЛСЯ на АГРОНАМА В с.ВЕ...
672  2014-10-03 00:25:00  Реєстрація користувача з ніком ДРЮНЯ неможлива...
627  2013-09-17 01:34:00                         Кто заберет на машине? Аня
648  2014-02-28 00:33:00    целоваться - это моё любимое дело  кто со мной?
664  2013-07-01 00:27:00  не живу  а существую. . Кто добавит в жизнь кр...

In [120]:
time['date']= pd.to_datetime(time['date'])

In [121]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [ ]:
time['hour'] = time['date'].dt.hour

In [122]:
time['min'] = time['date'].dt.minute
time['sec']= time['date'].dt.second
time.head()

,date,msg,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,11,0

In [123]:
#here date and time are in same column
#we can only extract time also.
time['time']=time['date'].dt.time
time.head()

,date,msg,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,11,0,23:11:00

In [124]:
# time difference
today - time['date']

0     4462 days 19:59:37.564669
1     4326 days 21:09:37.564669
2     4812 days 20:28:37.564669
3     4114 days 20:18:37.564669
4     4511 days 21:38:37.564669
                 ...
995   5101 days 19:59:37.564669
996   4422 days 21:35:37.564669
997   4887 days 21:12:37.564669
998   5003 days 21:15:37.564669
999   4275 days 21:24:37.564669
Name: date, Length: 1000, dtype: timedelta64[us]

In [126]:
#in second
(today - time['date'])/np.timedelta64(1,'s')

0      3.855888e+08
1      3.738426e+08
2      4.158305e+08
3      3.555227e+08
4      3.898283e+08
           ...
995    4.407984e+08
996    3.821385e+08
997    4.223132e+08
998    4.323357e+08
999    3.694371e+08
Name: date, Length: 1000, dtype: float64

In [127]:
#in minute
(today - time['date'])/np.timedelta64(1,'m')

0      6.426480e+06
1      6.230710e+06
2      6.930509e+06
3      5.925379e+06
4      6.497139e+06
           ...
995    7.346640e+06
996    6.368976e+06
997    7.038553e+06
998    7.205596e+06
999    6.157285e+06
Name: date, Length: 1000, dtype: float64

In [128]:
#in hours
(today - time['date'])/np.timedelta64(1,'h')

0      107107.993768
1      103845.160435
2      115508.477101
3       98756.310435
4      108285.643768
           ...
995    122443.993768
996    106149.593768
997    117309.210435
998    120093.260435
999    102621.410435
Name: date, Length: 1000, dtype: float64