In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import KNNImputer, SimpleImputer

In [2]:
df = pd.read_csv('dataset/titanic_dataset.csv', usecols=['Age','Pclass','Fare','Survived'])

In [3]:
df.sample(5)

     Survived  Pclass   Age     Fare
96          0       1  71.0  34.6542
538         0       3   NaN  14.5000
116         0       3  70.5   7.7500
635         1       2  28.0  13.0000
114         0       3  17.0  14.4583

In [4]:
df.isnull().mean() * 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [5]:
X = df.drop('Survived',axis=1)
y=df.Survived

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42, test_size=0.2)

In [7]:
X_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [8]:
knn= KNNImputer()
X_train_imputed = knn.fit_transform(X_train)
X_test_imputed = knn.transform(X_test)

In [9]:
pd.DataFrame(X_train_imputed, columns=X_train.columns).sample(5)

     Pclass   Age     Fare
552     3.0  22.7   8.0500
609     1.0  49.0  76.7292
481     2.0  31.0  26.2500
583     3.0  35.0   7.8958
633     1.0  38.0  71.2833

In [10]:
X_train_imputed

array([[  1.    ,  45.5   ,  28.5   ],
       [  2.    ,  23.    ,  13.    ],
       [  3.    ,  32.    ,   7.925 ],
       ...,
       [  3.    ,  41.    ,  14.1083],
       [  1.    ,  14.    , 120.    ],
       [  1.    ,  21.    ,  77.2875]], shape=(712, 3))

In [11]:
lr = LogisticRegression()
lr.fit(X_train_imputed,y_train)
y_pred = lr.predict(X_test_imputed)
accuracy_score(y_pred,y_test)

0.7430167597765364

In [12]:
#comparing with mean imputation using simple imputation
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

lr= LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(y_pred,y_test)

0.7374301675977654

### MICE

In [13]:
from sklearn.experimental import enable_iterative_imputer

from sklearn.impute import IterativeImputer

In [15]:
data = {
    'age':[25,30,np.nan , 40,35],
    'salary':[50000,np.nan,60000,80000,np.nan],
    'experience':[2,5,7,np.nan,10]
}
df = pd.DataFrame(data)
df

    age   salary  experience
0  25.0  50000.0         2.0
1  30.0      NaN         5.0
2   NaN  60000.0         7.0
3  40.0  80000.0         NaN
4  35.0      NaN        10.0

In [18]:
impute = IterativeImputer(max_iter=10,random_state=42)
df_imputed = impute.fit_transform(df)
df_imputed = pd.DataFrame(df_imputed,columns=df.columns)
np.round(df_imputed,2)

    age    salary  experience
0  25.0  50000.00        2.00
1  30.0  59995.05        5.00
2  30.0  60000.00        7.00
3  40.0  80000.00       13.98
4  35.0  70000.06       10.00