In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv('titanic_dataset.csv')

In [4]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
164,1056,0,2,"Peruschitz, Rev. Joseph Maria",male,41.0,0,0,237393,13.0000,NaN,S
253,1145,0,3,"Salander, Mr. Karl Johan",male,24.0,0,0,7266,9.3250,NaN,S
93,985,0,3,"Guest, Mr. Robert",male,NaN,0,0,376563,8.0500,NaN,S
15,907,1,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
189,1081,0,2,"Veal, Mr. James",male,40.0,0,0,28221,13.0000,NaN,S

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
df.shape

(418, 12)

In [10]:
df.dropna(inplace = True)

In [12]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
122,1014,1,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.0,1,0,13236,57.7500,C28,C
57,949,0,3,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0,0,348122,7.6500,F G63,S
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
75,967,0,1,"Keeping, Mr. Edwin",male,32.5,0,0,113503,211.5000,C132,C
208,1100,1,1,"Rosenbaum, Miss. Edith Louise",female,33.0,0,0,PC 17613,27.7208,A11,C

In [14]:
# # here, cabin has mixture of both numberical and alphabets.
# # no  mix of both (type 2-> copy)

# # for data: 1 2 3 A C 3 G 7 S
# df['column'].unique()

# #extract numerical:
# df['numerical_col'] = pd.to_numeric(df['column'], errors='coerce', downcast = 'integer')
# #extract categorical part:
# df['categorical_col'] = np.where(df['numerical_col'].isnull(), df['numerical_col'], np.nan)

In [16]:
# Cabin -> mixture
df['Cabin'].unique()

<StringArray>
[            'B45',             'E31', 'B57 B59 B63 B66',             'B36',
             'A21',             'C78',             'D19',              'A9',
             'D15',             'C31',     'C23 C25 C27',           'F G63',
             'B61',             'C53',             'D43',            'C130',
            'C132',            'C101',         'C55 C57',             'B71',
             'C46',            'C116',               'F',             'A29',
              'G6',              'C6',             'C28',             'C51',
             'C54',             'C97',             'D22',             'B10',
              'F4',             'E45',             'E52',             'D30',
         'B58 B60',             'E34',         'C62 C64',             'A11',
             'B11',             'C80',             'F33',             'C85',
             'D37',             'C86',             'D21',             'C89',
             'A34',             'B26',         'C22 C26',             'B69',
             'C32',             'B78',           'F E57',              'F2',
             'A18',            'C106',     'B51 B53 B55',         'D10 D12',
             'E60',             'E50',         'E39 E41',     'B52 B54 B56',
             'C39',             'B24',             'D28',             'B41',
              'C7',             'D40',             'D38',            'C105']
Length: 72, dtype: str

In [18]:
df['cabin_num'] = df['Cabin'].str.extract('(\d+)') #to captures numerical part
df['cabin_cat'] = df['Cabin'].str[0] #capture the first letter

df.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_4283/2360203888.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['cabin_num'] = df['Cabin'].str.extract('(\d+)') #to captures numerical part

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,cabin_num,cabin_cat
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S,45,B
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,31,E
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,57,B
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C,36,B
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S,21,A

In [ ]:
# we can also do in ticket too.